site_name: gtracr Documentation
site_url : https://gtracr.readthedocs.io
site_author : Keito Watanabe
repo_url : https://github.com/kwat0308/gtracr
nav:
    - Home: 'index.md'
    - Background : 'background.md'
    - Evaluating a Single Trajectory : 'trajectory.md'
    - Geomagnetic Cutoff Rigidities : 'geomagnetic_cutoffs.md'
    - Benchmarks : 'benchmarks.md'
    - License : 'license.md'
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust

